version: '3.8'

services:
  mysqldb:
    image: 'mysql:latest'
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./db:/var/lib/mysql

volumes:
  db:
  config:
